syntax = "proto3";
import "Base.proto";
option java_multiple_files = true;

package org.jh.forum.api.dubbo;

/**
 * 发表评论请求参数
 */
message PublishCommentReq {
  int64 post_id = 1;
  int64 parent_id = 2;
  int64 target_id = 3;
  string content = 4;
  string attachment_url = 5;
  repeated int64 at_list = 6;
}

/**
 * 发表评论响应参数
 */
message PublishCommentResp {
  int64 commentId = 1;
}

/**
 * 点赞评论请求参数
 */
message UpvoteCommentReq {
  int64 commentId = 1;
}

/**
 * 点赞评论响应参数
 */
message UpvoteCommentResp {
  bool status = 1;
}

/**
 * 评论服务接口
 */
service CommentService {
  /**
   * 发表评论方法定义
   */
  rpc publishComment(PublishCommentReq) returns (ServiceResult);

  /**
   * 点赞评论方法定义
   */
  rpc upvoteComment(UpvoteCommentReq) returns (ServiceResult);
}
