syntax = "proto3";
import "Base.proto";
option java_multiple_files = true;

package org.jh.forum.api.dubbo;

/**
 * 请求参数
 */
message PublishPostReq {
  string uid = 1;
  string title = 2;
  string context = 3;
  repeated string tagList = 4;
}

/**
 * 响应参数
 */
message PublishPostResp {
  string postId = 1;
}

/**
 * 服务接口
 */
service CorrectDataService {

  /**
   * 发布帖子方法定义
   */
  rpc publishPost(PublishPostReq) returns (ServiceResult);

  /**
   * 发布评论方法定义
   */
  rpc publishComment(PublishPostReq) returns (ServiceResult);

}
