syntax = "proto3";
import "Base.proto";
option java_multiple_files = true;

package org.jh.forum.api.dubbo;

message CheckBlake3Req {
  string blake3 = 1;
}

message FileId {
  int64 fileId = 1;
}

message CreateFileReq{
  string objectKey = 1;
  string blake3 = 2;
}

message CreateAttachmentReq{
  int64 fileId = 1;
  string type = 2;
  string filename = 3;
}

message AttachmentId{
  int64 attachmentId = 1;
}

message GetAttachmentInfoResp{
  string url = 1;
  string type = 2;
  string filename = 3;
}

service FileService {
  rpc checkBlake3(CheckBlake3Req) returns (ServiceResult);
  rpc createFile(CreateFileReq) returns (ServiceResult);
  rpc createAttachment(CreateAttachmentReq) returns (ServiceResult);
  rpc getAttachmentInfo(AttachmentId) returns (ServiceResult);
}
